### ISSUE TITLE
Dockerized command isn't cross platform

### ISSUE THREAD

**Issue by KnicKnic** [traefik/traefik-migration-tool#20]
[Dockerized command](https://hub.docker.com/r/containous/traefik-migration-tool/tags?page=1&ordering=last_updated) isn't cross platform - only linux/amd64

was trying to run conversion step on my raspberry pi 3+ arm/v6

**Comment by ldez** [comment]
Hello,

yes, our image is not multi-arch.

The binaries for each arch can be found here: https://github.com/traefik/traefik-migration-tool/releases

**Comment by ldez** [comment]
I made some improvements and now the image is multi-arch.

https://hub.docker.com/repository/docker/traefik/traefik-migration-tool/tags?page=1&ordering=last_updated
