### ISSUE TITLE
Dockerized command

### ISSUE THREAD

**Issue by PurpleBabar** [traefik/traefik-migration-tool#6]
Hey folks !

Thanks for the tool it's been helpful :) 
I've containerized the traefik migration tool :) would you like me to do a PR ? 

Cheerz

**Comment by ldez** [comment]
Hello,

> Thanks for the tool it's been helpful :)
Thank you for giving us this kind of positive feedback, it's appreciated.

yes you can create a PR, some constraints:
- create a Dockerfile oriented for the Docker hub auto-build.
- add documentation.

Thank you.

**Comment by PurpleBabar** [comment]
Will do :) Thanks :)

**Comment by kevinpollet** [comment]
Closed by #8
